//			$(".showup1").hover(function(){
//				$(".showdown1").attr("src","img/play_small_b.png");
//			})
//			$(".showup1").mouseleave(function(){
//				$(".showdown1").attr("src","img/play_small_h.png");
//			})
//			$(".showup2").hover(function(){
//				$(".showdown2").attr("src","img/play_small_b.png");
//			})
//			$(".showup2").mouseleave(function(){
//				$(".showdown2").attr("src","img/play_small_h.png");
//			})
//			$(".showup3").hover(function(){
//				$(".showdown3").attr("src","img/play_small_b.png");
//			})
//			$(".showup3").mouseleave(function(){
//				$(".showdown3").attr("src","img/play_small_h.png");
//			})
//			$(".showup4").hover(function(){
//				$(".showdown4").attr("src","img/play_small_b.png");
//			})
//			$(".showup4").mouseleave(function(){
//				$(".showdown4").attr("src","img/play_small_h.png");
//			})
//			$(".showup5").hover(function(){
//				$(".showdown5").attr("src","img/play_small_b.png");
//			})
//			$(".showup5").mouseleave(function(){
//				$(".showdown5").attr("src","img/play_small_h.png");
//			})
//			$(".showup6").hover(function(){
//				$(".showdown6").attr("src","img/play_small_b.png");
//			})
//			$(".showup6").mouseleave(function(){
//				$(".showdown6").attr("src","img/play_small_h.png");
//			})
//			$(".showup7").hover(function(){
//				$(".showdown7").attr("src","img/play_small_b.png");
//			})
//			$(".showup7").mouseleave(function(){
//				$(".showdown7").attr("src","img/play_small_h.png");
//			})
//			$(".showup8").hover(function(){
//				$(".showdown8").attr("src","img/play_small_b.png");
//			})
//			$(".showup8").mouseleave(function(){
//				$(".showdown8").attr("src","img/play_small_h.png");
//			})
//			$(".showup9").hover(function(){
//				$(".showdown9").attr("src","img/play_small_b.png");
//			})
//			$(".showup9").mouseleave(function(){
//				$(".showdown9").attr("src","img/play_small_h.png");
//			})