        $(".footer1").hover(function(){
			$(".footer1").attr("src","img/home/mail_h.jpg");
		})
		$(".footer1").mouseleave(function(){
			$(".footer1").attr("src","img/home/mail.jpg");
		})
		$(".footer2").hover(function(){
			$(".footer2").attr("src","img/home/facebook_h.jpg");
		})
		$(".footer2").mouseleave(function(){
			$(".footer2").attr("src","img/home/facebook.jpg");
		})
		$(".footer3").hover(function(){
			$(".footer3").attr("src","img/home/youtube_h.jpg");
		})
		$(".footer3").mouseleave(function(){
			$(".footer3").attr("src","img/home/youtube.jpg");
		})
		$(".footer4").hover(function(){
			$(".footer4").attr("src","img/home/linkedln_h.jpg");
		})
		$(".footer4").mouseleave(function(){
			$(".footer4").attr("src","img/home/linkedln.jpg");
		})
		$(".footer5").hover(function(){
			$(".footer5").attr("src","img/home/twitter_h.jpg");
		})
		$(".footer5").mouseleave(function(){
			$(".footer5").attr("src","img/home/twitter.jpg");
		})